// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ProtoMessage.proto

package proto;

public final class ProtoMessageOuterClass {
  private ProtoMessageOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface ProtoMessageOrBuilder extends
      // @@protoc_insertion_point(interface_extends:proto.ProtoMessage)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>.proto.ProtoMessage.Type type = 1;</code>
     */
    int getTypeValue();
    /**
     * <code>.proto.ProtoMessage.Type type = 1;</code>
     */
    proto.ProtoMessageOuterClass.ProtoMessage.Type getType();

    /**
     * <code>repeated .proto.PatientRequest patientRequest = 2;</code>
     */
    java.util.List<proto.ProtoMessageOuterClass.PatientRequest> 
        getPatientRequestList();
    /**
     * <code>repeated .proto.PatientRequest patientRequest = 2;</code>
     */
    proto.ProtoMessageOuterClass.PatientRequest getPatientRequest(int index);
    /**
     * <code>repeated .proto.PatientRequest patientRequest = 2;</code>
     */
    int getPatientRequestCount();
    /**
     * <code>repeated .proto.PatientRequest patientRequest = 2;</code>
     */
    java.util.List<? extends proto.ProtoMessageOuterClass.PatientRequestOrBuilder> 
        getPatientRequestOrBuilderList();
    /**
     * <code>repeated .proto.PatientRequest patientRequest = 2;</code>
     */
    proto.ProtoMessageOuterClass.PatientRequestOrBuilder getPatientRequestOrBuilder(
        int index);

    /**
     * <code>repeated .proto.PatientResponse patientResponse = 3;</code>
     */
    java.util.List<proto.ProtoMessageOuterClass.PatientResponse> 
        getPatientResponseList();
    /**
     * <code>repeated .proto.PatientResponse patientResponse = 3;</code>
     */
    proto.ProtoMessageOuterClass.PatientResponse getPatientResponse(int index);
    /**
     * <code>repeated .proto.PatientResponse patientResponse = 3;</code>
     */
    int getPatientResponseCount();
    /**
     * <code>repeated .proto.PatientResponse patientResponse = 3;</code>
     */
    java.util.List<? extends proto.ProtoMessageOuterClass.PatientResponseOrBuilder> 
        getPatientResponseOrBuilderList();
    /**
     * <code>repeated .proto.PatientResponse patientResponse = 3;</code>
     */
    proto.ProtoMessageOuterClass.PatientResponseOrBuilder getPatientResponseOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code proto.ProtoMessage}
   */
  public  static final class ProtoMessage extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:proto.ProtoMessage)
      ProtoMessageOrBuilder {
    // Use ProtoMessage.newBuilder() to construct.
    private ProtoMessage(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private ProtoMessage() {
      type_ = 0;
      patientRequest_ = java.util.Collections.emptyList();
      patientResponse_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private ProtoMessage(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              int rawValue = input.readEnum();

              type_ = rawValue;
              break;
            }
            case 18: {
              if (!((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
                patientRequest_ = new java.util.ArrayList<proto.ProtoMessageOuterClass.PatientRequest>();
                mutable_bitField0_ |= 0x00000002;
              }
              patientRequest_.add(
                  input.readMessage(proto.ProtoMessageOuterClass.PatientRequest.parser(), extensionRegistry));
              break;
            }
            case 26: {
              if (!((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
                patientResponse_ = new java.util.ArrayList<proto.ProtoMessageOuterClass.PatientResponse>();
                mutable_bitField0_ |= 0x00000004;
              }
              patientResponse_.add(
                  input.readMessage(proto.ProtoMessageOuterClass.PatientResponse.parser(), extensionRegistry));
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
          patientRequest_ = java.util.Collections.unmodifiableList(patientRequest_);
        }
        if (((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
          patientResponse_ = java.util.Collections.unmodifiableList(patientResponse_);
        }
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return proto.ProtoMessageOuterClass.internal_static_proto_ProtoMessage_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return proto.ProtoMessageOuterClass.internal_static_proto_ProtoMessage_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              proto.ProtoMessageOuterClass.ProtoMessage.class, proto.ProtoMessageOuterClass.ProtoMessage.Builder.class);
    }

    /**
     * Protobuf enum {@code proto.ProtoMessage.Type}
     */
    public enum Type
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <code>request = 0;</code>
       */
      request(0),
      /**
       * <code>response = 1;</code>
       */
      response(1),
      UNRECOGNIZED(-1),
      ;

      /**
       * <code>request = 0;</code>
       */
      public static final int request_VALUE = 0;
      /**
       * <code>response = 1;</code>
       */
      public static final int response_VALUE = 1;


      public final int getNumber() {
        if (this == UNRECOGNIZED) {
          throw new java.lang.IllegalArgumentException(
              "Can't get the number of an unknown enum value.");
        }
        return value;
      }

      /**
       * @deprecated Use {@link #forNumber(int)} instead.
       */
      @java.lang.Deprecated
      public static Type valueOf(int value) {
        return forNumber(value);
      }

      public static Type forNumber(int value) {
        switch (value) {
          case 0: return request;
          case 1: return response;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<Type>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static final com.google.protobuf.Internal.EnumLiteMap<
          Type> internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<Type>() {
              public Type findValueByNumber(int number) {
                return Type.forNumber(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(ordinal());
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return proto.ProtoMessageOuterClass.ProtoMessage.getDescriptor().getEnumTypes().get(0);
      }

      private static final Type[] VALUES = values();

      public static Type valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        if (desc.getIndex() == -1) {
          return UNRECOGNIZED;
        }
        return VALUES[desc.getIndex()];
      }

      private final int value;

      private Type(int value) {
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:proto.ProtoMessage.Type)
    }

    private int bitField0_;
    public static final int TYPE_FIELD_NUMBER = 1;
    private int type_;
    /**
     * <code>.proto.ProtoMessage.Type type = 1;</code>
     */
    public int getTypeValue() {
      return type_;
    }
    /**
     * <code>.proto.ProtoMessage.Type type = 1;</code>
     */
    public proto.ProtoMessageOuterClass.ProtoMessage.Type getType() {
      proto.ProtoMessageOuterClass.ProtoMessage.Type result = proto.ProtoMessageOuterClass.ProtoMessage.Type.valueOf(type_);
      return result == null ? proto.ProtoMessageOuterClass.ProtoMessage.Type.UNRECOGNIZED : result;
    }

    public static final int PATIENTREQUEST_FIELD_NUMBER = 2;
    private java.util.List<proto.ProtoMessageOuterClass.PatientRequest> patientRequest_;
    /**
     * <code>repeated .proto.PatientRequest patientRequest = 2;</code>
     */
    public java.util.List<proto.ProtoMessageOuterClass.PatientRequest> getPatientRequestList() {
      return patientRequest_;
    }
    /**
     * <code>repeated .proto.PatientRequest patientRequest = 2;</code>
     */
    public java.util.List<? extends proto.ProtoMessageOuterClass.PatientRequestOrBuilder> 
        getPatientRequestOrBuilderList() {
      return patientRequest_;
    }
    /**
     * <code>repeated .proto.PatientRequest patientRequest = 2;</code>
     */
    public int getPatientRequestCount() {
      return patientRequest_.size();
    }
    /**
     * <code>repeated .proto.PatientRequest patientRequest = 2;</code>
     */
    public proto.ProtoMessageOuterClass.PatientRequest getPatientRequest(int index) {
      return patientRequest_.get(index);
    }
    /**
     * <code>repeated .proto.PatientRequest patientRequest = 2;</code>
     */
    public proto.ProtoMessageOuterClass.PatientRequestOrBuilder getPatientRequestOrBuilder(
        int index) {
      return patientRequest_.get(index);
    }

    public static final int PATIENTRESPONSE_FIELD_NUMBER = 3;
    private java.util.List<proto.ProtoMessageOuterClass.PatientResponse> patientResponse_;
    /**
     * <code>repeated .proto.PatientResponse patientResponse = 3;</code>
     */
    public java.util.List<proto.ProtoMessageOuterClass.PatientResponse> getPatientResponseList() {
      return patientResponse_;
    }
    /**
     * <code>repeated .proto.PatientResponse patientResponse = 3;</code>
     */
    public java.util.List<? extends proto.ProtoMessageOuterClass.PatientResponseOrBuilder> 
        getPatientResponseOrBuilderList() {
      return patientResponse_;
    }
    /**
     * <code>repeated .proto.PatientResponse patientResponse = 3;</code>
     */
    public int getPatientResponseCount() {
      return patientResponse_.size();
    }
    /**
     * <code>repeated .proto.PatientResponse patientResponse = 3;</code>
     */
    public proto.ProtoMessageOuterClass.PatientResponse getPatientResponse(int index) {
      return patientResponse_.get(index);
    }
    /**
     * <code>repeated .proto.PatientResponse patientResponse = 3;</code>
     */
    public proto.ProtoMessageOuterClass.PatientResponseOrBuilder getPatientResponseOrBuilder(
        int index) {
      return patientResponse_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (type_ != proto.ProtoMessageOuterClass.ProtoMessage.Type.request.getNumber()) {
        output.writeEnum(1, type_);
      }
      for (int i = 0; i < patientRequest_.size(); i++) {
        output.writeMessage(2, patientRequest_.get(i));
      }
      for (int i = 0; i < patientResponse_.size(); i++) {
        output.writeMessage(3, patientResponse_.get(i));
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (type_ != proto.ProtoMessageOuterClass.ProtoMessage.Type.request.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(1, type_);
      }
      for (int i = 0; i < patientRequest_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, patientRequest_.get(i));
      }
      for (int i = 0; i < patientResponse_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(3, patientResponse_.get(i));
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof proto.ProtoMessageOuterClass.ProtoMessage)) {
        return super.equals(obj);
      }
      proto.ProtoMessageOuterClass.ProtoMessage other = (proto.ProtoMessageOuterClass.ProtoMessage) obj;

      boolean result = true;
      result = result && type_ == other.type_;
      result = result && getPatientRequestList()
          .equals(other.getPatientRequestList());
      result = result && getPatientResponseList()
          .equals(other.getPatientResponseList());
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + TYPE_FIELD_NUMBER;
      hash = (53 * hash) + type_;
      if (getPatientRequestCount() > 0) {
        hash = (37 * hash) + PATIENTREQUEST_FIELD_NUMBER;
        hash = (53 * hash) + getPatientRequestList().hashCode();
      }
      if (getPatientResponseCount() > 0) {
        hash = (37 * hash) + PATIENTRESPONSE_FIELD_NUMBER;
        hash = (53 * hash) + getPatientResponseList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static proto.ProtoMessageOuterClass.ProtoMessage parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static proto.ProtoMessageOuterClass.ProtoMessage parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static proto.ProtoMessageOuterClass.ProtoMessage parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static proto.ProtoMessageOuterClass.ProtoMessage parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static proto.ProtoMessageOuterClass.ProtoMessage parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static proto.ProtoMessageOuterClass.ProtoMessage parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static proto.ProtoMessageOuterClass.ProtoMessage parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static proto.ProtoMessageOuterClass.ProtoMessage parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static proto.ProtoMessageOuterClass.ProtoMessage parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static proto.ProtoMessageOuterClass.ProtoMessage parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static proto.ProtoMessageOuterClass.ProtoMessage parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static proto.ProtoMessageOuterClass.ProtoMessage parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(proto.ProtoMessageOuterClass.ProtoMessage prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code proto.ProtoMessage}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:proto.ProtoMessage)
        proto.ProtoMessageOuterClass.ProtoMessageOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return proto.ProtoMessageOuterClass.internal_static_proto_ProtoMessage_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return proto.ProtoMessageOuterClass.internal_static_proto_ProtoMessage_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                proto.ProtoMessageOuterClass.ProtoMessage.class, proto.ProtoMessageOuterClass.ProtoMessage.Builder.class);
      }

      // Construct using proto.ProtoMessageOuterClass.ProtoMessage.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getPatientRequestFieldBuilder();
          getPatientResponseFieldBuilder();
        }
      }
      public Builder clear() {
        super.clear();
        type_ = 0;

        if (patientRequestBuilder_ == null) {
          patientRequest_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000002);
        } else {
          patientRequestBuilder_.clear();
        }
        if (patientResponseBuilder_ == null) {
          patientResponse_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000004);
        } else {
          patientResponseBuilder_.clear();
        }
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return proto.ProtoMessageOuterClass.internal_static_proto_ProtoMessage_descriptor;
      }

      public proto.ProtoMessageOuterClass.ProtoMessage getDefaultInstanceForType() {
        return proto.ProtoMessageOuterClass.ProtoMessage.getDefaultInstance();
      }

      public proto.ProtoMessageOuterClass.ProtoMessage build() {
        proto.ProtoMessageOuterClass.ProtoMessage result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public proto.ProtoMessageOuterClass.ProtoMessage buildPartial() {
        proto.ProtoMessageOuterClass.ProtoMessage result = new proto.ProtoMessageOuterClass.ProtoMessage(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        result.type_ = type_;
        if (patientRequestBuilder_ == null) {
          if (((bitField0_ & 0x00000002) == 0x00000002)) {
            patientRequest_ = java.util.Collections.unmodifiableList(patientRequest_);
            bitField0_ = (bitField0_ & ~0x00000002);
          }
          result.patientRequest_ = patientRequest_;
        } else {
          result.patientRequest_ = patientRequestBuilder_.build();
        }
        if (patientResponseBuilder_ == null) {
          if (((bitField0_ & 0x00000004) == 0x00000004)) {
            patientResponse_ = java.util.Collections.unmodifiableList(patientResponse_);
            bitField0_ = (bitField0_ & ~0x00000004);
          }
          result.patientResponse_ = patientResponse_;
        } else {
          result.patientResponse_ = patientResponseBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof proto.ProtoMessageOuterClass.ProtoMessage) {
          return mergeFrom((proto.ProtoMessageOuterClass.ProtoMessage)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(proto.ProtoMessageOuterClass.ProtoMessage other) {
        if (other == proto.ProtoMessageOuterClass.ProtoMessage.getDefaultInstance()) return this;
        if (other.type_ != 0) {
          setTypeValue(other.getTypeValue());
        }
        if (patientRequestBuilder_ == null) {
          if (!other.patientRequest_.isEmpty()) {
            if (patientRequest_.isEmpty()) {
              patientRequest_ = other.patientRequest_;
              bitField0_ = (bitField0_ & ~0x00000002);
            } else {
              ensurePatientRequestIsMutable();
              patientRequest_.addAll(other.patientRequest_);
            }
            onChanged();
          }
        } else {
          if (!other.patientRequest_.isEmpty()) {
            if (patientRequestBuilder_.isEmpty()) {
              patientRequestBuilder_.dispose();
              patientRequestBuilder_ = null;
              patientRequest_ = other.patientRequest_;
              bitField0_ = (bitField0_ & ~0x00000002);
              patientRequestBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getPatientRequestFieldBuilder() : null;
            } else {
              patientRequestBuilder_.addAllMessages(other.patientRequest_);
            }
          }
        }
        if (patientResponseBuilder_ == null) {
          if (!other.patientResponse_.isEmpty()) {
            if (patientResponse_.isEmpty()) {
              patientResponse_ = other.patientResponse_;
              bitField0_ = (bitField0_ & ~0x00000004);
            } else {
              ensurePatientResponseIsMutable();
              patientResponse_.addAll(other.patientResponse_);
            }
            onChanged();
          }
        } else {
          if (!other.patientResponse_.isEmpty()) {
            if (patientResponseBuilder_.isEmpty()) {
              patientResponseBuilder_.dispose();
              patientResponseBuilder_ = null;
              patientResponse_ = other.patientResponse_;
              bitField0_ = (bitField0_ & ~0x00000004);
              patientResponseBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getPatientResponseFieldBuilder() : null;
            } else {
              patientResponseBuilder_.addAllMessages(other.patientResponse_);
            }
          }
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        proto.ProtoMessageOuterClass.ProtoMessage parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (proto.ProtoMessageOuterClass.ProtoMessage) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private int type_ = 0;
      /**
       * <code>.proto.ProtoMessage.Type type = 1;</code>
       */
      public int getTypeValue() {
        return type_;
      }
      /**
       * <code>.proto.ProtoMessage.Type type = 1;</code>
       */
      public Builder setTypeValue(int value) {
        type_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>.proto.ProtoMessage.Type type = 1;</code>
       */
      public proto.ProtoMessageOuterClass.ProtoMessage.Type getType() {
        proto.ProtoMessageOuterClass.ProtoMessage.Type result = proto.ProtoMessageOuterClass.ProtoMessage.Type.valueOf(type_);
        return result == null ? proto.ProtoMessageOuterClass.ProtoMessage.Type.UNRECOGNIZED : result;
      }
      /**
       * <code>.proto.ProtoMessage.Type type = 1;</code>
       */
      public Builder setType(proto.ProtoMessageOuterClass.ProtoMessage.Type value) {
        if (value == null) {
          throw new NullPointerException();
        }
        
        type_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>.proto.ProtoMessage.Type type = 1;</code>
       */
      public Builder clearType() {
        
        type_ = 0;
        onChanged();
        return this;
      }

      private java.util.List<proto.ProtoMessageOuterClass.PatientRequest> patientRequest_ =
        java.util.Collections.emptyList();
      private void ensurePatientRequestIsMutable() {
        if (!((bitField0_ & 0x00000002) == 0x00000002)) {
          patientRequest_ = new java.util.ArrayList<proto.ProtoMessageOuterClass.PatientRequest>(patientRequest_);
          bitField0_ |= 0x00000002;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          proto.ProtoMessageOuterClass.PatientRequest, proto.ProtoMessageOuterClass.PatientRequest.Builder, proto.ProtoMessageOuterClass.PatientRequestOrBuilder> patientRequestBuilder_;

      /**
       * <code>repeated .proto.PatientRequest patientRequest = 2;</code>
       */
      public java.util.List<proto.ProtoMessageOuterClass.PatientRequest> getPatientRequestList() {
        if (patientRequestBuilder_ == null) {
          return java.util.Collections.unmodifiableList(patientRequest_);
        } else {
          return patientRequestBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .proto.PatientRequest patientRequest = 2;</code>
       */
      public int getPatientRequestCount() {
        if (patientRequestBuilder_ == null) {
          return patientRequest_.size();
        } else {
          return patientRequestBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .proto.PatientRequest patientRequest = 2;</code>
       */
      public proto.ProtoMessageOuterClass.PatientRequest getPatientRequest(int index) {
        if (patientRequestBuilder_ == null) {
          return patientRequest_.get(index);
        } else {
          return patientRequestBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .proto.PatientRequest patientRequest = 2;</code>
       */
      public Builder setPatientRequest(
          int index, proto.ProtoMessageOuterClass.PatientRequest value) {
        if (patientRequestBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensurePatientRequestIsMutable();
          patientRequest_.set(index, value);
          onChanged();
        } else {
          patientRequestBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .proto.PatientRequest patientRequest = 2;</code>
       */
      public Builder setPatientRequest(
          int index, proto.ProtoMessageOuterClass.PatientRequest.Builder builderForValue) {
        if (patientRequestBuilder_ == null) {
          ensurePatientRequestIsMutable();
          patientRequest_.set(index, builderForValue.build());
          onChanged();
        } else {
          patientRequestBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .proto.PatientRequest patientRequest = 2;</code>
       */
      public Builder addPatientRequest(proto.ProtoMessageOuterClass.PatientRequest value) {
        if (patientRequestBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensurePatientRequestIsMutable();
          patientRequest_.add(value);
          onChanged();
        } else {
          patientRequestBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .proto.PatientRequest patientRequest = 2;</code>
       */
      public Builder addPatientRequest(
          int index, proto.ProtoMessageOuterClass.PatientRequest value) {
        if (patientRequestBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensurePatientRequestIsMutable();
          patientRequest_.add(index, value);
          onChanged();
        } else {
          patientRequestBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .proto.PatientRequest patientRequest = 2;</code>
       */
      public Builder addPatientRequest(
          proto.ProtoMessageOuterClass.PatientRequest.Builder builderForValue) {
        if (patientRequestBuilder_ == null) {
          ensurePatientRequestIsMutable();
          patientRequest_.add(builderForValue.build());
          onChanged();
        } else {
          patientRequestBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .proto.PatientRequest patientRequest = 2;</code>
       */
      public Builder addPatientRequest(
          int index, proto.ProtoMessageOuterClass.PatientRequest.Builder builderForValue) {
        if (patientRequestBuilder_ == null) {
          ensurePatientRequestIsMutable();
          patientRequest_.add(index, builderForValue.build());
          onChanged();
        } else {
          patientRequestBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .proto.PatientRequest patientRequest = 2;</code>
       */
      public Builder addAllPatientRequest(
          java.lang.Iterable<? extends proto.ProtoMessageOuterClass.PatientRequest> values) {
        if (patientRequestBuilder_ == null) {
          ensurePatientRequestIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, patientRequest_);
          onChanged();
        } else {
          patientRequestBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .proto.PatientRequest patientRequest = 2;</code>
       */
      public Builder clearPatientRequest() {
        if (patientRequestBuilder_ == null) {
          patientRequest_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000002);
          onChanged();
        } else {
          patientRequestBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .proto.PatientRequest patientRequest = 2;</code>
       */
      public Builder removePatientRequest(int index) {
        if (patientRequestBuilder_ == null) {
          ensurePatientRequestIsMutable();
          patientRequest_.remove(index);
          onChanged();
        } else {
          patientRequestBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .proto.PatientRequest patientRequest = 2;</code>
       */
      public proto.ProtoMessageOuterClass.PatientRequest.Builder getPatientRequestBuilder(
          int index) {
        return getPatientRequestFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .proto.PatientRequest patientRequest = 2;</code>
       */
      public proto.ProtoMessageOuterClass.PatientRequestOrBuilder getPatientRequestOrBuilder(
          int index) {
        if (patientRequestBuilder_ == null) {
          return patientRequest_.get(index);  } else {
          return patientRequestBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .proto.PatientRequest patientRequest = 2;</code>
       */
      public java.util.List<? extends proto.ProtoMessageOuterClass.PatientRequestOrBuilder> 
           getPatientRequestOrBuilderList() {
        if (patientRequestBuilder_ != null) {
          return patientRequestBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(patientRequest_);
        }
      }
      /**
       * <code>repeated .proto.PatientRequest patientRequest = 2;</code>
       */
      public proto.ProtoMessageOuterClass.PatientRequest.Builder addPatientRequestBuilder() {
        return getPatientRequestFieldBuilder().addBuilder(
            proto.ProtoMessageOuterClass.PatientRequest.getDefaultInstance());
      }
      /**
       * <code>repeated .proto.PatientRequest patientRequest = 2;</code>
       */
      public proto.ProtoMessageOuterClass.PatientRequest.Builder addPatientRequestBuilder(
          int index) {
        return getPatientRequestFieldBuilder().addBuilder(
            index, proto.ProtoMessageOuterClass.PatientRequest.getDefaultInstance());
      }
      /**
       * <code>repeated .proto.PatientRequest patientRequest = 2;</code>
       */
      public java.util.List<proto.ProtoMessageOuterClass.PatientRequest.Builder> 
           getPatientRequestBuilderList() {
        return getPatientRequestFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          proto.ProtoMessageOuterClass.PatientRequest, proto.ProtoMessageOuterClass.PatientRequest.Builder, proto.ProtoMessageOuterClass.PatientRequestOrBuilder> 
          getPatientRequestFieldBuilder() {
        if (patientRequestBuilder_ == null) {
          patientRequestBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              proto.ProtoMessageOuterClass.PatientRequest, proto.ProtoMessageOuterClass.PatientRequest.Builder, proto.ProtoMessageOuterClass.PatientRequestOrBuilder>(
                  patientRequest_,
                  ((bitField0_ & 0x00000002) == 0x00000002),
                  getParentForChildren(),
                  isClean());
          patientRequest_ = null;
        }
        return patientRequestBuilder_;
      }

      private java.util.List<proto.ProtoMessageOuterClass.PatientResponse> patientResponse_ =
        java.util.Collections.emptyList();
      private void ensurePatientResponseIsMutable() {
        if (!((bitField0_ & 0x00000004) == 0x00000004)) {
          patientResponse_ = new java.util.ArrayList<proto.ProtoMessageOuterClass.PatientResponse>(patientResponse_);
          bitField0_ |= 0x00000004;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          proto.ProtoMessageOuterClass.PatientResponse, proto.ProtoMessageOuterClass.PatientResponse.Builder, proto.ProtoMessageOuterClass.PatientResponseOrBuilder> patientResponseBuilder_;

      /**
       * <code>repeated .proto.PatientResponse patientResponse = 3;</code>
       */
      public java.util.List<proto.ProtoMessageOuterClass.PatientResponse> getPatientResponseList() {
        if (patientResponseBuilder_ == null) {
          return java.util.Collections.unmodifiableList(patientResponse_);
        } else {
          return patientResponseBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .proto.PatientResponse patientResponse = 3;</code>
       */
      public int getPatientResponseCount() {
        if (patientResponseBuilder_ == null) {
          return patientResponse_.size();
        } else {
          return patientResponseBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .proto.PatientResponse patientResponse = 3;</code>
       */
      public proto.ProtoMessageOuterClass.PatientResponse getPatientResponse(int index) {
        if (patientResponseBuilder_ == null) {
          return patientResponse_.get(index);
        } else {
          return patientResponseBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .proto.PatientResponse patientResponse = 3;</code>
       */
      public Builder setPatientResponse(
          int index, proto.ProtoMessageOuterClass.PatientResponse value) {
        if (patientResponseBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensurePatientResponseIsMutable();
          patientResponse_.set(index, value);
          onChanged();
        } else {
          patientResponseBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .proto.PatientResponse patientResponse = 3;</code>
       */
      public Builder setPatientResponse(
          int index, proto.ProtoMessageOuterClass.PatientResponse.Builder builderForValue) {
        if (patientResponseBuilder_ == null) {
          ensurePatientResponseIsMutable();
          patientResponse_.set(index, builderForValue.build());
          onChanged();
        } else {
          patientResponseBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .proto.PatientResponse patientResponse = 3;</code>
       */
      public Builder addPatientResponse(proto.ProtoMessageOuterClass.PatientResponse value) {
        if (patientResponseBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensurePatientResponseIsMutable();
          patientResponse_.add(value);
          onChanged();
        } else {
          patientResponseBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .proto.PatientResponse patientResponse = 3;</code>
       */
      public Builder addPatientResponse(
          int index, proto.ProtoMessageOuterClass.PatientResponse value) {
        if (patientResponseBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensurePatientResponseIsMutable();
          patientResponse_.add(index, value);
          onChanged();
        } else {
          patientResponseBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .proto.PatientResponse patientResponse = 3;</code>
       */
      public Builder addPatientResponse(
          proto.ProtoMessageOuterClass.PatientResponse.Builder builderForValue) {
        if (patientResponseBuilder_ == null) {
          ensurePatientResponseIsMutable();
          patientResponse_.add(builderForValue.build());
          onChanged();
        } else {
          patientResponseBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .proto.PatientResponse patientResponse = 3;</code>
       */
      public Builder addPatientResponse(
          int index, proto.ProtoMessageOuterClass.PatientResponse.Builder builderForValue) {
        if (patientResponseBuilder_ == null) {
          ensurePatientResponseIsMutable();
          patientResponse_.add(index, builderForValue.build());
          onChanged();
        } else {
          patientResponseBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .proto.PatientResponse patientResponse = 3;</code>
       */
      public Builder addAllPatientResponse(
          java.lang.Iterable<? extends proto.ProtoMessageOuterClass.PatientResponse> values) {
        if (patientResponseBuilder_ == null) {
          ensurePatientResponseIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, patientResponse_);
          onChanged();
        } else {
          patientResponseBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .proto.PatientResponse patientResponse = 3;</code>
       */
      public Builder clearPatientResponse() {
        if (patientResponseBuilder_ == null) {
          patientResponse_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000004);
          onChanged();
        } else {
          patientResponseBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .proto.PatientResponse patientResponse = 3;</code>
       */
      public Builder removePatientResponse(int index) {
        if (patientResponseBuilder_ == null) {
          ensurePatientResponseIsMutable();
          patientResponse_.remove(index);
          onChanged();
        } else {
          patientResponseBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .proto.PatientResponse patientResponse = 3;</code>
       */
      public proto.ProtoMessageOuterClass.PatientResponse.Builder getPatientResponseBuilder(
          int index) {
        return getPatientResponseFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .proto.PatientResponse patientResponse = 3;</code>
       */
      public proto.ProtoMessageOuterClass.PatientResponseOrBuilder getPatientResponseOrBuilder(
          int index) {
        if (patientResponseBuilder_ == null) {
          return patientResponse_.get(index);  } else {
          return patientResponseBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .proto.PatientResponse patientResponse = 3;</code>
       */
      public java.util.List<? extends proto.ProtoMessageOuterClass.PatientResponseOrBuilder> 
           getPatientResponseOrBuilderList() {
        if (patientResponseBuilder_ != null) {
          return patientResponseBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(patientResponse_);
        }
      }
      /**
       * <code>repeated .proto.PatientResponse patientResponse = 3;</code>
       */
      public proto.ProtoMessageOuterClass.PatientResponse.Builder addPatientResponseBuilder() {
        return getPatientResponseFieldBuilder().addBuilder(
            proto.ProtoMessageOuterClass.PatientResponse.getDefaultInstance());
      }
      /**
       * <code>repeated .proto.PatientResponse patientResponse = 3;</code>
       */
      public proto.ProtoMessageOuterClass.PatientResponse.Builder addPatientResponseBuilder(
          int index) {
        return getPatientResponseFieldBuilder().addBuilder(
            index, proto.ProtoMessageOuterClass.PatientResponse.getDefaultInstance());
      }
      /**
       * <code>repeated .proto.PatientResponse patientResponse = 3;</code>
       */
      public java.util.List<proto.ProtoMessageOuterClass.PatientResponse.Builder> 
           getPatientResponseBuilderList() {
        return getPatientResponseFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          proto.ProtoMessageOuterClass.PatientResponse, proto.ProtoMessageOuterClass.PatientResponse.Builder, proto.ProtoMessageOuterClass.PatientResponseOrBuilder> 
          getPatientResponseFieldBuilder() {
        if (patientResponseBuilder_ == null) {
          patientResponseBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              proto.ProtoMessageOuterClass.PatientResponse, proto.ProtoMessageOuterClass.PatientResponse.Builder, proto.ProtoMessageOuterClass.PatientResponseOrBuilder>(
                  patientResponse_,
                  ((bitField0_ & 0x00000004) == 0x00000004),
                  getParentForChildren(),
                  isClean());
          patientResponse_ = null;
        }
        return patientResponseBuilder_;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:proto.ProtoMessage)
    }

    // @@protoc_insertion_point(class_scope:proto.ProtoMessage)
    private static final proto.ProtoMessageOuterClass.ProtoMessage DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new proto.ProtoMessageOuterClass.ProtoMessage();
    }

    public static proto.ProtoMessageOuterClass.ProtoMessage getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<ProtoMessage>
        PARSER = new com.google.protobuf.AbstractParser<ProtoMessage>() {
      public ProtoMessage parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new ProtoMessage(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<ProtoMessage> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<ProtoMessage> getParserForType() {
      return PARSER;
    }

    public proto.ProtoMessageOuterClass.ProtoMessage getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface PatientRequestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:proto.PatientRequest)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>uint32 patientNumber = 1;</code>
     */
    int getPatientNumber();
  }
  /**
   * Protobuf type {@code proto.PatientRequest}
   */
  public  static final class PatientRequest extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:proto.PatientRequest)
      PatientRequestOrBuilder {
    // Use PatientRequest.newBuilder() to construct.
    private PatientRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private PatientRequest() {
      patientNumber_ = 0;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private PatientRequest(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 8: {

              patientNumber_ = input.readUInt32();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return proto.ProtoMessageOuterClass.internal_static_proto_PatientRequest_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return proto.ProtoMessageOuterClass.internal_static_proto_PatientRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              proto.ProtoMessageOuterClass.PatientRequest.class, proto.ProtoMessageOuterClass.PatientRequest.Builder.class);
    }

    public static final int PATIENTNUMBER_FIELD_NUMBER = 1;
    private int patientNumber_;
    /**
     * <code>uint32 patientNumber = 1;</code>
     */
    public int getPatientNumber() {
      return patientNumber_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (patientNumber_ != 0) {
        output.writeUInt32(1, patientNumber_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (patientNumber_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(1, patientNumber_);
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof proto.ProtoMessageOuterClass.PatientRequest)) {
        return super.equals(obj);
      }
      proto.ProtoMessageOuterClass.PatientRequest other = (proto.ProtoMessageOuterClass.PatientRequest) obj;

      boolean result = true;
      result = result && (getPatientNumber()
          == other.getPatientNumber());
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + PATIENTNUMBER_FIELD_NUMBER;
      hash = (53 * hash) + getPatientNumber();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static proto.ProtoMessageOuterClass.PatientRequest parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static proto.ProtoMessageOuterClass.PatientRequest parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static proto.ProtoMessageOuterClass.PatientRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static proto.ProtoMessageOuterClass.PatientRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static proto.ProtoMessageOuterClass.PatientRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static proto.ProtoMessageOuterClass.PatientRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static proto.ProtoMessageOuterClass.PatientRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static proto.ProtoMessageOuterClass.PatientRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static proto.ProtoMessageOuterClass.PatientRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static proto.ProtoMessageOuterClass.PatientRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static proto.ProtoMessageOuterClass.PatientRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static proto.ProtoMessageOuterClass.PatientRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(proto.ProtoMessageOuterClass.PatientRequest prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code proto.PatientRequest}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:proto.PatientRequest)
        proto.ProtoMessageOuterClass.PatientRequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return proto.ProtoMessageOuterClass.internal_static_proto_PatientRequest_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return proto.ProtoMessageOuterClass.internal_static_proto_PatientRequest_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                proto.ProtoMessageOuterClass.PatientRequest.class, proto.ProtoMessageOuterClass.PatientRequest.Builder.class);
      }

      // Construct using proto.ProtoMessageOuterClass.PatientRequest.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        patientNumber_ = 0;

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return proto.ProtoMessageOuterClass.internal_static_proto_PatientRequest_descriptor;
      }

      public proto.ProtoMessageOuterClass.PatientRequest getDefaultInstanceForType() {
        return proto.ProtoMessageOuterClass.PatientRequest.getDefaultInstance();
      }

      public proto.ProtoMessageOuterClass.PatientRequest build() {
        proto.ProtoMessageOuterClass.PatientRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public proto.ProtoMessageOuterClass.PatientRequest buildPartial() {
        proto.ProtoMessageOuterClass.PatientRequest result = new proto.ProtoMessageOuterClass.PatientRequest(this);
        result.patientNumber_ = patientNumber_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof proto.ProtoMessageOuterClass.PatientRequest) {
          return mergeFrom((proto.ProtoMessageOuterClass.PatientRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(proto.ProtoMessageOuterClass.PatientRequest other) {
        if (other == proto.ProtoMessageOuterClass.PatientRequest.getDefaultInstance()) return this;
        if (other.getPatientNumber() != 0) {
          setPatientNumber(other.getPatientNumber());
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        proto.ProtoMessageOuterClass.PatientRequest parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (proto.ProtoMessageOuterClass.PatientRequest) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int patientNumber_ ;
      /**
       * <code>uint32 patientNumber = 1;</code>
       */
      public int getPatientNumber() {
        return patientNumber_;
      }
      /**
       * <code>uint32 patientNumber = 1;</code>
       */
      public Builder setPatientNumber(int value) {
        
        patientNumber_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>uint32 patientNumber = 1;</code>
       */
      public Builder clearPatientNumber() {
        
        patientNumber_ = 0;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:proto.PatientRequest)
    }

    // @@protoc_insertion_point(class_scope:proto.PatientRequest)
    private static final proto.ProtoMessageOuterClass.PatientRequest DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new proto.ProtoMessageOuterClass.PatientRequest();
    }

    public static proto.ProtoMessageOuterClass.PatientRequest getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<PatientRequest>
        PARSER = new com.google.protobuf.AbstractParser<PatientRequest>() {
      public PatientRequest parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new PatientRequest(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<PatientRequest> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<PatientRequest> getParserForType() {
      return PARSER;
    }

    public proto.ProtoMessageOuterClass.PatientRequest getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface PatientResponseOrBuilder extends
      // @@protoc_insertion_point(interface_extends:proto.PatientResponse)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>.proto.ProtoPatient patient = 1;</code>
     */
    boolean hasPatient();
    /**
     * <code>.proto.ProtoPatient patient = 1;</code>
     */
    proto.ProtoPatientOuterClass.ProtoPatient getPatient();
    /**
     * <code>.proto.ProtoPatient patient = 1;</code>
     */
    proto.ProtoPatientOuterClass.ProtoPatientOrBuilder getPatientOrBuilder();
  }
  /**
   * Protobuf type {@code proto.PatientResponse}
   */
  public  static final class PatientResponse extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:proto.PatientResponse)
      PatientResponseOrBuilder {
    // Use PatientResponse.newBuilder() to construct.
    private PatientResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private PatientResponse() {
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private PatientResponse(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              proto.ProtoPatientOuterClass.ProtoPatient.Builder subBuilder = null;
              if (patient_ != null) {
                subBuilder = patient_.toBuilder();
              }
              patient_ = input.readMessage(proto.ProtoPatientOuterClass.ProtoPatient.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(patient_);
                patient_ = subBuilder.buildPartial();
              }

              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return proto.ProtoMessageOuterClass.internal_static_proto_PatientResponse_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return proto.ProtoMessageOuterClass.internal_static_proto_PatientResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              proto.ProtoMessageOuterClass.PatientResponse.class, proto.ProtoMessageOuterClass.PatientResponse.Builder.class);
    }

    public static final int PATIENT_FIELD_NUMBER = 1;
    private proto.ProtoPatientOuterClass.ProtoPatient patient_;
    /**
     * <code>.proto.ProtoPatient patient = 1;</code>
     */
    public boolean hasPatient() {
      return patient_ != null;
    }
    /**
     * <code>.proto.ProtoPatient patient = 1;</code>
     */
    public proto.ProtoPatientOuterClass.ProtoPatient getPatient() {
      return patient_ == null ? proto.ProtoPatientOuterClass.ProtoPatient.getDefaultInstance() : patient_;
    }
    /**
     * <code>.proto.ProtoPatient patient = 1;</code>
     */
    public proto.ProtoPatientOuterClass.ProtoPatientOrBuilder getPatientOrBuilder() {
      return getPatient();
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (patient_ != null) {
        output.writeMessage(1, getPatient());
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (patient_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, getPatient());
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof proto.ProtoMessageOuterClass.PatientResponse)) {
        return super.equals(obj);
      }
      proto.ProtoMessageOuterClass.PatientResponse other = (proto.ProtoMessageOuterClass.PatientResponse) obj;

      boolean result = true;
      result = result && (hasPatient() == other.hasPatient());
      if (hasPatient()) {
        result = result && getPatient()
            .equals(other.getPatient());
      }
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasPatient()) {
        hash = (37 * hash) + PATIENT_FIELD_NUMBER;
        hash = (53 * hash) + getPatient().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static proto.ProtoMessageOuterClass.PatientResponse parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static proto.ProtoMessageOuterClass.PatientResponse parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static proto.ProtoMessageOuterClass.PatientResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static proto.ProtoMessageOuterClass.PatientResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static proto.ProtoMessageOuterClass.PatientResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static proto.ProtoMessageOuterClass.PatientResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static proto.ProtoMessageOuterClass.PatientResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static proto.ProtoMessageOuterClass.PatientResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static proto.ProtoMessageOuterClass.PatientResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static proto.ProtoMessageOuterClass.PatientResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static proto.ProtoMessageOuterClass.PatientResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static proto.ProtoMessageOuterClass.PatientResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(proto.ProtoMessageOuterClass.PatientResponse prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code proto.PatientResponse}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:proto.PatientResponse)
        proto.ProtoMessageOuterClass.PatientResponseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return proto.ProtoMessageOuterClass.internal_static_proto_PatientResponse_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return proto.ProtoMessageOuterClass.internal_static_proto_PatientResponse_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                proto.ProtoMessageOuterClass.PatientResponse.class, proto.ProtoMessageOuterClass.PatientResponse.Builder.class);
      }

      // Construct using proto.ProtoMessageOuterClass.PatientResponse.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        if (patientBuilder_ == null) {
          patient_ = null;
        } else {
          patient_ = null;
          patientBuilder_ = null;
        }
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return proto.ProtoMessageOuterClass.internal_static_proto_PatientResponse_descriptor;
      }

      public proto.ProtoMessageOuterClass.PatientResponse getDefaultInstanceForType() {
        return proto.ProtoMessageOuterClass.PatientResponse.getDefaultInstance();
      }

      public proto.ProtoMessageOuterClass.PatientResponse build() {
        proto.ProtoMessageOuterClass.PatientResponse result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public proto.ProtoMessageOuterClass.PatientResponse buildPartial() {
        proto.ProtoMessageOuterClass.PatientResponse result = new proto.ProtoMessageOuterClass.PatientResponse(this);
        if (patientBuilder_ == null) {
          result.patient_ = patient_;
        } else {
          result.patient_ = patientBuilder_.build();
        }
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof proto.ProtoMessageOuterClass.PatientResponse) {
          return mergeFrom((proto.ProtoMessageOuterClass.PatientResponse)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(proto.ProtoMessageOuterClass.PatientResponse other) {
        if (other == proto.ProtoMessageOuterClass.PatientResponse.getDefaultInstance()) return this;
        if (other.hasPatient()) {
          mergePatient(other.getPatient());
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        proto.ProtoMessageOuterClass.PatientResponse parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (proto.ProtoMessageOuterClass.PatientResponse) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private proto.ProtoPatientOuterClass.ProtoPatient patient_ = null;
      private com.google.protobuf.SingleFieldBuilderV3<
          proto.ProtoPatientOuterClass.ProtoPatient, proto.ProtoPatientOuterClass.ProtoPatient.Builder, proto.ProtoPatientOuterClass.ProtoPatientOrBuilder> patientBuilder_;
      /**
       * <code>.proto.ProtoPatient patient = 1;</code>
       */
      public boolean hasPatient() {
        return patientBuilder_ != null || patient_ != null;
      }
      /**
       * <code>.proto.ProtoPatient patient = 1;</code>
       */
      public proto.ProtoPatientOuterClass.ProtoPatient getPatient() {
        if (patientBuilder_ == null) {
          return patient_ == null ? proto.ProtoPatientOuterClass.ProtoPatient.getDefaultInstance() : patient_;
        } else {
          return patientBuilder_.getMessage();
        }
      }
      /**
       * <code>.proto.ProtoPatient patient = 1;</code>
       */
      public Builder setPatient(proto.ProtoPatientOuterClass.ProtoPatient value) {
        if (patientBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          patient_ = value;
          onChanged();
        } else {
          patientBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>.proto.ProtoPatient patient = 1;</code>
       */
      public Builder setPatient(
          proto.ProtoPatientOuterClass.ProtoPatient.Builder builderForValue) {
        if (patientBuilder_ == null) {
          patient_ = builderForValue.build();
          onChanged();
        } else {
          patientBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>.proto.ProtoPatient patient = 1;</code>
       */
      public Builder mergePatient(proto.ProtoPatientOuterClass.ProtoPatient value) {
        if (patientBuilder_ == null) {
          if (patient_ != null) {
            patient_ =
              proto.ProtoPatientOuterClass.ProtoPatient.newBuilder(patient_).mergeFrom(value).buildPartial();
          } else {
            patient_ = value;
          }
          onChanged();
        } else {
          patientBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>.proto.ProtoPatient patient = 1;</code>
       */
      public Builder clearPatient() {
        if (patientBuilder_ == null) {
          patient_ = null;
          onChanged();
        } else {
          patient_ = null;
          patientBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>.proto.ProtoPatient patient = 1;</code>
       */
      public proto.ProtoPatientOuterClass.ProtoPatient.Builder getPatientBuilder() {
        
        onChanged();
        return getPatientFieldBuilder().getBuilder();
      }
      /**
       * <code>.proto.ProtoPatient patient = 1;</code>
       */
      public proto.ProtoPatientOuterClass.ProtoPatientOrBuilder getPatientOrBuilder() {
        if (patientBuilder_ != null) {
          return patientBuilder_.getMessageOrBuilder();
        } else {
          return patient_ == null ?
              proto.ProtoPatientOuterClass.ProtoPatient.getDefaultInstance() : patient_;
        }
      }
      /**
       * <code>.proto.ProtoPatient patient = 1;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          proto.ProtoPatientOuterClass.ProtoPatient, proto.ProtoPatientOuterClass.ProtoPatient.Builder, proto.ProtoPatientOuterClass.ProtoPatientOrBuilder> 
          getPatientFieldBuilder() {
        if (patientBuilder_ == null) {
          patientBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              proto.ProtoPatientOuterClass.ProtoPatient, proto.ProtoPatientOuterClass.ProtoPatient.Builder, proto.ProtoPatientOuterClass.ProtoPatientOrBuilder>(
                  getPatient(),
                  getParentForChildren(),
                  isClean());
          patient_ = null;
        }
        return patientBuilder_;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:proto.PatientResponse)
    }

    // @@protoc_insertion_point(class_scope:proto.PatientResponse)
    private static final proto.ProtoMessageOuterClass.PatientResponse DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new proto.ProtoMessageOuterClass.PatientResponse();
    }

    public static proto.ProtoMessageOuterClass.PatientResponse getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<PatientResponse>
        PARSER = new com.google.protobuf.AbstractParser<PatientResponse>() {
      public PatientResponse parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new PatientResponse(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<PatientResponse> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<PatientResponse> getParserForType() {
      return PARSER;
    }

    public proto.ProtoMessageOuterClass.PatientResponse getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_proto_ProtoMessage_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_proto_ProtoMessage_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_proto_PatientRequest_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_proto_PatientRequest_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_proto_PatientResponse_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_proto_PatientResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\022ProtoMessage.proto\022\005proto\032\022ProtoPatien" +
      "t.proto\"\271\001\n\014ProtoMessage\022&\n\004type\030\001 \001(\0162\030" +
      ".proto.ProtoMessage.Type\022-\n\016patientReque" +
      "st\030\002 \003(\0132\025.proto.PatientRequest\022/\n\017patie" +
      "ntResponse\030\003 \003(\0132\026.proto.PatientResponse" +
      "\"!\n\004Type\022\013\n\007request\020\000\022\014\n\010response\020\001\"\'\n\016P" +
      "atientRequest\022\025\n\rpatientNumber\030\001 \001(\r\"7\n\017" +
      "PatientResponse\022$\n\007patient\030\001 \001(\0132\023.proto" +
      ".ProtoPatientb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          proto.ProtoPatientOuterClass.getDescriptor(),
        }, assigner);
    internal_static_proto_ProtoMessage_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_proto_ProtoMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_proto_ProtoMessage_descriptor,
        new java.lang.String[] { "Type", "PatientRequest", "PatientResponse", });
    internal_static_proto_PatientRequest_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_proto_PatientRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_proto_PatientRequest_descriptor,
        new java.lang.String[] { "PatientNumber", });
    internal_static_proto_PatientResponse_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_proto_PatientResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_proto_PatientResponse_descriptor,
        new java.lang.String[] { "Patient", });
    proto.ProtoPatientOuterClass.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
