/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.3.9-dev at Sun Jun  4 21:32:04 2017. */

#include "message.pb.h"

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif



const pb_field_t proto_espData_fields[5] = {
    PB_FIELD(  1, UINT32  , SINGULAR, STATIC  , FIRST, proto_espData, x, x, 0),
    PB_FIELD(  2, UINT32  , SINGULAR, STATIC  , OTHER, proto_espData, y, x, 0),
    PB_FIELD(  3, UINT32  , SINGULAR, STATIC  , OTHER, proto_espData, z, y, 0),
    PB_FIELD(  4, UINT32  , SINGULAR, STATIC  , OTHER, proto_espData, m, z, 0),
    PB_LAST_FIELD
};


/* @@protoc_insertion_point(eof) */
