// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ProtoMessage.proto

package proto;

public final class ProtoMessageOuterClass {
  private ProtoMessageOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface ProtoMessageOrBuilder extends
      // @@protoc_insertion_point(interface_extends:proto.ProtoMessage)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>.proto.PatientRequest patientRequest = 1;</code>
     */
    proto.ProtoMessageOuterClass.PatientRequest getPatientRequest();
    /**
     * <code>.proto.PatientRequest patientRequest = 1;</code>
     */
    proto.ProtoMessageOuterClass.PatientRequestOrBuilder getPatientRequestOrBuilder();

    /**
     * <code>.proto.PatientResponse patientResponse = 2;</code>
     */
    proto.ProtoMessageOuterClass.PatientResponse getPatientResponse();
    /**
     * <code>.proto.PatientResponse patientResponse = 2;</code>
     */
    proto.ProtoMessageOuterClass.PatientResponseOrBuilder getPatientResponseOrBuilder();

    /**
     * <code>.proto.Sensor sensor = 3;</code>
     */
    proto.ProtoMessageOuterClass.Sensor getSensor();
    /**
     * <code>.proto.Sensor sensor = 3;</code>
     */
    proto.ProtoMessageOuterClass.SensorOrBuilder getSensorOrBuilder();

    public proto.ProtoMessageOuterClass.ProtoMessage.MessageCase getMessageCase();
  }
  /**
   * Protobuf type {@code proto.ProtoMessage}
   */
  public  static final class ProtoMessage extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:proto.ProtoMessage)
      ProtoMessageOrBuilder {
    // Use ProtoMessage.newBuilder() to construct.
    private ProtoMessage(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private ProtoMessage() {
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private ProtoMessage(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              proto.ProtoMessageOuterClass.PatientRequest.Builder subBuilder = null;
              if (messageCase_ == 1) {
                subBuilder = ((proto.ProtoMessageOuterClass.PatientRequest) message_).toBuilder();
              }
              message_ =
                  input.readMessage(proto.ProtoMessageOuterClass.PatientRequest.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom((proto.ProtoMessageOuterClass.PatientRequest) message_);
                message_ = subBuilder.buildPartial();
              }
              messageCase_ = 1;
              break;
            }
            case 18: {
              proto.ProtoMessageOuterClass.PatientResponse.Builder subBuilder = null;
              if (messageCase_ == 2) {
                subBuilder = ((proto.ProtoMessageOuterClass.PatientResponse) message_).toBuilder();
              }
              message_ =
                  input.readMessage(proto.ProtoMessageOuterClass.PatientResponse.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom((proto.ProtoMessageOuterClass.PatientResponse) message_);
                message_ = subBuilder.buildPartial();
              }
              messageCase_ = 2;
              break;
            }
            case 26: {
              proto.ProtoMessageOuterClass.Sensor.Builder subBuilder = null;
              if (messageCase_ == 3) {
                subBuilder = ((proto.ProtoMessageOuterClass.Sensor) message_).toBuilder();
              }
              message_ =
                  input.readMessage(proto.ProtoMessageOuterClass.Sensor.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom((proto.ProtoMessageOuterClass.Sensor) message_);
                message_ = subBuilder.buildPartial();
              }
              messageCase_ = 3;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return proto.ProtoMessageOuterClass.internal_static_proto_ProtoMessage_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return proto.ProtoMessageOuterClass.internal_static_proto_ProtoMessage_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              proto.ProtoMessageOuterClass.ProtoMessage.class, proto.ProtoMessageOuterClass.ProtoMessage.Builder.class);
    }

    private int messageCase_ = 0;
    private java.lang.Object message_;
    public enum MessageCase
        implements com.google.protobuf.Internal.EnumLite {
      PATIENTREQUEST(1),
      PATIENTRESPONSE(2),
      SENSOR(3),
      MESSAGE_NOT_SET(0);
      private final int value;
      private MessageCase(int value) {
        this.value = value;
      }
      /**
       * @deprecated Use {@link #forNumber(int)} instead.
       */
      @java.lang.Deprecated
      public static MessageCase valueOf(int value) {
        return forNumber(value);
      }

      public static MessageCase forNumber(int value) {
        switch (value) {
          case 1: return PATIENTREQUEST;
          case 2: return PATIENTRESPONSE;
          case 3: return SENSOR;
          case 0: return MESSAGE_NOT_SET;
          default: return null;
        }
      }
      public int getNumber() {
        return this.value;
      }
    };

    public MessageCase
    getMessageCase() {
      return MessageCase.forNumber(
          messageCase_);
    }

    public static final int PATIENTREQUEST_FIELD_NUMBER = 1;
    /**
     * <code>.proto.PatientRequest patientRequest = 1;</code>
     */
    public proto.ProtoMessageOuterClass.PatientRequest getPatientRequest() {
      if (messageCase_ == 1) {
         return (proto.ProtoMessageOuterClass.PatientRequest) message_;
      }
      return proto.ProtoMessageOuterClass.PatientRequest.getDefaultInstance();
    }
    /**
     * <code>.proto.PatientRequest patientRequest = 1;</code>
     */
    public proto.ProtoMessageOuterClass.PatientRequestOrBuilder getPatientRequestOrBuilder() {
      if (messageCase_ == 1) {
         return (proto.ProtoMessageOuterClass.PatientRequest) message_;
      }
      return proto.ProtoMessageOuterClass.PatientRequest.getDefaultInstance();
    }

    public static final int PATIENTRESPONSE_FIELD_NUMBER = 2;
    /**
     * <code>.proto.PatientResponse patientResponse = 2;</code>
     */
    public proto.ProtoMessageOuterClass.PatientResponse getPatientResponse() {
      if (messageCase_ == 2) {
         return (proto.ProtoMessageOuterClass.PatientResponse) message_;
      }
      return proto.ProtoMessageOuterClass.PatientResponse.getDefaultInstance();
    }
    /**
     * <code>.proto.PatientResponse patientResponse = 2;</code>
     */
    public proto.ProtoMessageOuterClass.PatientResponseOrBuilder getPatientResponseOrBuilder() {
      if (messageCase_ == 2) {
         return (proto.ProtoMessageOuterClass.PatientResponse) message_;
      }
      return proto.ProtoMessageOuterClass.PatientResponse.getDefaultInstance();
    }

    public static final int SENSOR_FIELD_NUMBER = 3;
    /**
     * <code>.proto.Sensor sensor = 3;</code>
     */
    public proto.ProtoMessageOuterClass.Sensor getSensor() {
      if (messageCase_ == 3) {
         return (proto.ProtoMessageOuterClass.Sensor) message_;
      }
      return proto.ProtoMessageOuterClass.Sensor.getDefaultInstance();
    }
    /**
     * <code>.proto.Sensor sensor = 3;</code>
     */
    public proto.ProtoMessageOuterClass.SensorOrBuilder getSensorOrBuilder() {
      if (messageCase_ == 3) {
         return (proto.ProtoMessageOuterClass.Sensor) message_;
      }
      return proto.ProtoMessageOuterClass.Sensor.getDefaultInstance();
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (messageCase_ == 1) {
        output.writeMessage(1, (proto.ProtoMessageOuterClass.PatientRequest) message_);
      }
      if (messageCase_ == 2) {
        output.writeMessage(2, (proto.ProtoMessageOuterClass.PatientResponse) message_);
      }
      if (messageCase_ == 3) {
        output.writeMessage(3, (proto.ProtoMessageOuterClass.Sensor) message_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (messageCase_ == 1) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, (proto.ProtoMessageOuterClass.PatientRequest) message_);
      }
      if (messageCase_ == 2) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, (proto.ProtoMessageOuterClass.PatientResponse) message_);
      }
      if (messageCase_ == 3) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(3, (proto.ProtoMessageOuterClass.Sensor) message_);
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof proto.ProtoMessageOuterClass.ProtoMessage)) {
        return super.equals(obj);
      }
      proto.ProtoMessageOuterClass.ProtoMessage other = (proto.ProtoMessageOuterClass.ProtoMessage) obj;

      boolean result = true;
      result = result && getMessageCase().equals(
          other.getMessageCase());
      if (!result) return false;
      switch (messageCase_) {
        case 1:
          result = result && getPatientRequest()
              .equals(other.getPatientRequest());
          break;
        case 2:
          result = result && getPatientResponse()
              .equals(other.getPatientResponse());
          break;
        case 3:
          result = result && getSensor()
              .equals(other.getSensor());
          break;
        case 0:
        default:
      }
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      switch (messageCase_) {
        case 1:
          hash = (37 * hash) + PATIENTREQUEST_FIELD_NUMBER;
          hash = (53 * hash) + getPatientRequest().hashCode();
          break;
        case 2:
          hash = (37 * hash) + PATIENTRESPONSE_FIELD_NUMBER;
          hash = (53 * hash) + getPatientResponse().hashCode();
          break;
        case 3:
          hash = (37 * hash) + SENSOR_FIELD_NUMBER;
          hash = (53 * hash) + getSensor().hashCode();
          break;
        case 0:
        default:
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static proto.ProtoMessageOuterClass.ProtoMessage parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static proto.ProtoMessageOuterClass.ProtoMessage parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static proto.ProtoMessageOuterClass.ProtoMessage parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static proto.ProtoMessageOuterClass.ProtoMessage parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static proto.ProtoMessageOuterClass.ProtoMessage parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static proto.ProtoMessageOuterClass.ProtoMessage parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static proto.ProtoMessageOuterClass.ProtoMessage parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static proto.ProtoMessageOuterClass.ProtoMessage parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static proto.ProtoMessageOuterClass.ProtoMessage parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static proto.ProtoMessageOuterClass.ProtoMessage parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static proto.ProtoMessageOuterClass.ProtoMessage parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static proto.ProtoMessageOuterClass.ProtoMessage parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(proto.ProtoMessageOuterClass.ProtoMessage prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code proto.ProtoMessage}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:proto.ProtoMessage)
        proto.ProtoMessageOuterClass.ProtoMessageOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return proto.ProtoMessageOuterClass.internal_static_proto_ProtoMessage_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return proto.ProtoMessageOuterClass.internal_static_proto_ProtoMessage_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                proto.ProtoMessageOuterClass.ProtoMessage.class, proto.ProtoMessageOuterClass.ProtoMessage.Builder.class);
      }

      // Construct using proto.ProtoMessageOuterClass.ProtoMessage.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        messageCase_ = 0;
        message_ = null;
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return proto.ProtoMessageOuterClass.internal_static_proto_ProtoMessage_descriptor;
      }

      public proto.ProtoMessageOuterClass.ProtoMessage getDefaultInstanceForType() {
        return proto.ProtoMessageOuterClass.ProtoMessage.getDefaultInstance();
      }

      public proto.ProtoMessageOuterClass.ProtoMessage build() {
        proto.ProtoMessageOuterClass.ProtoMessage result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public proto.ProtoMessageOuterClass.ProtoMessage buildPartial() {
        proto.ProtoMessageOuterClass.ProtoMessage result = new proto.ProtoMessageOuterClass.ProtoMessage(this);
        if (messageCase_ == 1) {
          if (patientRequestBuilder_ == null) {
            result.message_ = message_;
          } else {
            result.message_ = patientRequestBuilder_.build();
          }
        }
        if (messageCase_ == 2) {
          if (patientResponseBuilder_ == null) {
            result.message_ = message_;
          } else {
            result.message_ = patientResponseBuilder_.build();
          }
        }
        if (messageCase_ == 3) {
          if (sensorBuilder_ == null) {
            result.message_ = message_;
          } else {
            result.message_ = sensorBuilder_.build();
          }
        }
        result.messageCase_ = messageCase_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof proto.ProtoMessageOuterClass.ProtoMessage) {
          return mergeFrom((proto.ProtoMessageOuterClass.ProtoMessage)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(proto.ProtoMessageOuterClass.ProtoMessage other) {
        if (other == proto.ProtoMessageOuterClass.ProtoMessage.getDefaultInstance()) return this;
        switch (other.getMessageCase()) {
          case PATIENTREQUEST: {
            mergePatientRequest(other.getPatientRequest());
            break;
          }
          case PATIENTRESPONSE: {
            mergePatientResponse(other.getPatientResponse());
            break;
          }
          case SENSOR: {
            mergeSensor(other.getSensor());
            break;
          }
          case MESSAGE_NOT_SET: {
            break;
          }
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        proto.ProtoMessageOuterClass.ProtoMessage parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (proto.ProtoMessageOuterClass.ProtoMessage) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int messageCase_ = 0;
      private java.lang.Object message_;
      public MessageCase
          getMessageCase() {
        return MessageCase.forNumber(
            messageCase_);
      }

      public Builder clearMessage() {
        messageCase_ = 0;
        message_ = null;
        onChanged();
        return this;
      }


      private com.google.protobuf.SingleFieldBuilderV3<
          proto.ProtoMessageOuterClass.PatientRequest, proto.ProtoMessageOuterClass.PatientRequest.Builder, proto.ProtoMessageOuterClass.PatientRequestOrBuilder> patientRequestBuilder_;
      /**
       * <code>.proto.PatientRequest patientRequest = 1;</code>
       */
      public proto.ProtoMessageOuterClass.PatientRequest getPatientRequest() {
        if (patientRequestBuilder_ == null) {
          if (messageCase_ == 1) {
            return (proto.ProtoMessageOuterClass.PatientRequest) message_;
          }
          return proto.ProtoMessageOuterClass.PatientRequest.getDefaultInstance();
        } else {
          if (messageCase_ == 1) {
            return patientRequestBuilder_.getMessage();
          }
          return proto.ProtoMessageOuterClass.PatientRequest.getDefaultInstance();
        }
      }
      /**
       * <code>.proto.PatientRequest patientRequest = 1;</code>
       */
      public Builder setPatientRequest(proto.ProtoMessageOuterClass.PatientRequest value) {
        if (patientRequestBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          message_ = value;
          onChanged();
        } else {
          patientRequestBuilder_.setMessage(value);
        }
        messageCase_ = 1;
        return this;
      }
      /**
       * <code>.proto.PatientRequest patientRequest = 1;</code>
       */
      public Builder setPatientRequest(
          proto.ProtoMessageOuterClass.PatientRequest.Builder builderForValue) {
        if (patientRequestBuilder_ == null) {
          message_ = builderForValue.build();
          onChanged();
        } else {
          patientRequestBuilder_.setMessage(builderForValue.build());
        }
        messageCase_ = 1;
        return this;
      }
      /**
       * <code>.proto.PatientRequest patientRequest = 1;</code>
       */
      public Builder mergePatientRequest(proto.ProtoMessageOuterClass.PatientRequest value) {
        if (patientRequestBuilder_ == null) {
          if (messageCase_ == 1 &&
              message_ != proto.ProtoMessageOuterClass.PatientRequest.getDefaultInstance()) {
            message_ = proto.ProtoMessageOuterClass.PatientRequest.newBuilder((proto.ProtoMessageOuterClass.PatientRequest) message_)
                .mergeFrom(value).buildPartial();
          } else {
            message_ = value;
          }
          onChanged();
        } else {
          if (messageCase_ == 1) {
            patientRequestBuilder_.mergeFrom(value);
          }
          patientRequestBuilder_.setMessage(value);
        }
        messageCase_ = 1;
        return this;
      }
      /**
       * <code>.proto.PatientRequest patientRequest = 1;</code>
       */
      public Builder clearPatientRequest() {
        if (patientRequestBuilder_ == null) {
          if (messageCase_ == 1) {
            messageCase_ = 0;
            message_ = null;
            onChanged();
          }
        } else {
          if (messageCase_ == 1) {
            messageCase_ = 0;
            message_ = null;
          }
          patientRequestBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>.proto.PatientRequest patientRequest = 1;</code>
       */
      public proto.ProtoMessageOuterClass.PatientRequest.Builder getPatientRequestBuilder() {
        return getPatientRequestFieldBuilder().getBuilder();
      }
      /**
       * <code>.proto.PatientRequest patientRequest = 1;</code>
       */
      public proto.ProtoMessageOuterClass.PatientRequestOrBuilder getPatientRequestOrBuilder() {
        if ((messageCase_ == 1) && (patientRequestBuilder_ != null)) {
          return patientRequestBuilder_.getMessageOrBuilder();
        } else {
          if (messageCase_ == 1) {
            return (proto.ProtoMessageOuterClass.PatientRequest) message_;
          }
          return proto.ProtoMessageOuterClass.PatientRequest.getDefaultInstance();
        }
      }
      /**
       * <code>.proto.PatientRequest patientRequest = 1;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          proto.ProtoMessageOuterClass.PatientRequest, proto.ProtoMessageOuterClass.PatientRequest.Builder, proto.ProtoMessageOuterClass.PatientRequestOrBuilder> 
          getPatientRequestFieldBuilder() {
        if (patientRequestBuilder_ == null) {
          if (!(messageCase_ == 1)) {
            message_ = proto.ProtoMessageOuterClass.PatientRequest.getDefaultInstance();
          }
          patientRequestBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              proto.ProtoMessageOuterClass.PatientRequest, proto.ProtoMessageOuterClass.PatientRequest.Builder, proto.ProtoMessageOuterClass.PatientRequestOrBuilder>(
                  (proto.ProtoMessageOuterClass.PatientRequest) message_,
                  getParentForChildren(),
                  isClean());
          message_ = null;
        }
        messageCase_ = 1;
        onChanged();;
        return patientRequestBuilder_;
      }

      private com.google.protobuf.SingleFieldBuilderV3<
          proto.ProtoMessageOuterClass.PatientResponse, proto.ProtoMessageOuterClass.PatientResponse.Builder, proto.ProtoMessageOuterClass.PatientResponseOrBuilder> patientResponseBuilder_;
      /**
       * <code>.proto.PatientResponse patientResponse = 2;</code>
       */
      public proto.ProtoMessageOuterClass.PatientResponse getPatientResponse() {
        if (patientResponseBuilder_ == null) {
          if (messageCase_ == 2) {
            return (proto.ProtoMessageOuterClass.PatientResponse) message_;
          }
          return proto.ProtoMessageOuterClass.PatientResponse.getDefaultInstance();
        } else {
          if (messageCase_ == 2) {
            return patientResponseBuilder_.getMessage();
          }
          return proto.ProtoMessageOuterClass.PatientResponse.getDefaultInstance();
        }
      }
      /**
       * <code>.proto.PatientResponse patientResponse = 2;</code>
       */
      public Builder setPatientResponse(proto.ProtoMessageOuterClass.PatientResponse value) {
        if (patientResponseBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          message_ = value;
          onChanged();
        } else {
          patientResponseBuilder_.setMessage(value);
        }
        messageCase_ = 2;
        return this;
      }
      /**
       * <code>.proto.PatientResponse patientResponse = 2;</code>
       */
      public Builder setPatientResponse(
          proto.ProtoMessageOuterClass.PatientResponse.Builder builderForValue) {
        if (patientResponseBuilder_ == null) {
          message_ = builderForValue.build();
          onChanged();
        } else {
          patientResponseBuilder_.setMessage(builderForValue.build());
        }
        messageCase_ = 2;
        return this;
      }
      /**
       * <code>.proto.PatientResponse patientResponse = 2;</code>
       */
      public Builder mergePatientResponse(proto.ProtoMessageOuterClass.PatientResponse value) {
        if (patientResponseBuilder_ == null) {
          if (messageCase_ == 2 &&
              message_ != proto.ProtoMessageOuterClass.PatientResponse.getDefaultInstance()) {
            message_ = proto.ProtoMessageOuterClass.PatientResponse.newBuilder((proto.ProtoMessageOuterClass.PatientResponse) message_)
                .mergeFrom(value).buildPartial();
          } else {
            message_ = value;
          }
          onChanged();
        } else {
          if (messageCase_ == 2) {
            patientResponseBuilder_.mergeFrom(value);
          }
          patientResponseBuilder_.setMessage(value);
        }
        messageCase_ = 2;
        return this;
      }
      /**
       * <code>.proto.PatientResponse patientResponse = 2;</code>
       */
      public Builder clearPatientResponse() {
        if (patientResponseBuilder_ == null) {
          if (messageCase_ == 2) {
            messageCase_ = 0;
            message_ = null;
            onChanged();
          }
        } else {
          if (messageCase_ == 2) {
            messageCase_ = 0;
            message_ = null;
          }
          patientResponseBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>.proto.PatientResponse patientResponse = 2;</code>
       */
      public proto.ProtoMessageOuterClass.PatientResponse.Builder getPatientResponseBuilder() {
        return getPatientResponseFieldBuilder().getBuilder();
      }
      /**
       * <code>.proto.PatientResponse patientResponse = 2;</code>
       */
      public proto.ProtoMessageOuterClass.PatientResponseOrBuilder getPatientResponseOrBuilder() {
        if ((messageCase_ == 2) && (patientResponseBuilder_ != null)) {
          return patientResponseBuilder_.getMessageOrBuilder();
        } else {
          if (messageCase_ == 2) {
            return (proto.ProtoMessageOuterClass.PatientResponse) message_;
          }
          return proto.ProtoMessageOuterClass.PatientResponse.getDefaultInstance();
        }
      }
      /**
       * <code>.proto.PatientResponse patientResponse = 2;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          proto.ProtoMessageOuterClass.PatientResponse, proto.ProtoMessageOuterClass.PatientResponse.Builder, proto.ProtoMessageOuterClass.PatientResponseOrBuilder> 
          getPatientResponseFieldBuilder() {
        if (patientResponseBuilder_ == null) {
          if (!(messageCase_ == 2)) {
            message_ = proto.ProtoMessageOuterClass.PatientResponse.getDefaultInstance();
          }
          patientResponseBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              proto.ProtoMessageOuterClass.PatientResponse, proto.ProtoMessageOuterClass.PatientResponse.Builder, proto.ProtoMessageOuterClass.PatientResponseOrBuilder>(
                  (proto.ProtoMessageOuterClass.PatientResponse) message_,
                  getParentForChildren(),
                  isClean());
          message_ = null;
        }
        messageCase_ = 2;
        onChanged();;
        return patientResponseBuilder_;
      }

      private com.google.protobuf.SingleFieldBuilderV3<
          proto.ProtoMessageOuterClass.Sensor, proto.ProtoMessageOuterClass.Sensor.Builder, proto.ProtoMessageOuterClass.SensorOrBuilder> sensorBuilder_;
      /**
       * <code>.proto.Sensor sensor = 3;</code>
       */
      public proto.ProtoMessageOuterClass.Sensor getSensor() {
        if (sensorBuilder_ == null) {
          if (messageCase_ == 3) {
            return (proto.ProtoMessageOuterClass.Sensor) message_;
          }
          return proto.ProtoMessageOuterClass.Sensor.getDefaultInstance();
        } else {
          if (messageCase_ == 3) {
            return sensorBuilder_.getMessage();
          }
          return proto.ProtoMessageOuterClass.Sensor.getDefaultInstance();
        }
      }
      /**
       * <code>.proto.Sensor sensor = 3;</code>
       */
      public Builder setSensor(proto.ProtoMessageOuterClass.Sensor value) {
        if (sensorBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          message_ = value;
          onChanged();
        } else {
          sensorBuilder_.setMessage(value);
        }
        messageCase_ = 3;
        return this;
      }
      /**
       * <code>.proto.Sensor sensor = 3;</code>
       */
      public Builder setSensor(
          proto.ProtoMessageOuterClass.Sensor.Builder builderForValue) {
        if (sensorBuilder_ == null) {
          message_ = builderForValue.build();
          onChanged();
        } else {
          sensorBuilder_.setMessage(builderForValue.build());
        }
        messageCase_ = 3;
        return this;
      }
      /**
       * <code>.proto.Sensor sensor = 3;</code>
       */
      public Builder mergeSensor(proto.ProtoMessageOuterClass.Sensor value) {
        if (sensorBuilder_ == null) {
          if (messageCase_ == 3 &&
              message_ != proto.ProtoMessageOuterClass.Sensor.getDefaultInstance()) {
            message_ = proto.ProtoMessageOuterClass.Sensor.newBuilder((proto.ProtoMessageOuterClass.Sensor) message_)
                .mergeFrom(value).buildPartial();
          } else {
            message_ = value;
          }
          onChanged();
        } else {
          if (messageCase_ == 3) {
            sensorBuilder_.mergeFrom(value);
          }
          sensorBuilder_.setMessage(value);
        }
        messageCase_ = 3;
        return this;
      }
      /**
       * <code>.proto.Sensor sensor = 3;</code>
       */
      public Builder clearSensor() {
        if (sensorBuilder_ == null) {
          if (messageCase_ == 3) {
            messageCase_ = 0;
            message_ = null;
            onChanged();
          }
        } else {
          if (messageCase_ == 3) {
            messageCase_ = 0;
            message_ = null;
          }
          sensorBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>.proto.Sensor sensor = 3;</code>
       */
      public proto.ProtoMessageOuterClass.Sensor.Builder getSensorBuilder() {
        return getSensorFieldBuilder().getBuilder();
      }
      /**
       * <code>.proto.Sensor sensor = 3;</code>
       */
      public proto.ProtoMessageOuterClass.SensorOrBuilder getSensorOrBuilder() {
        if ((messageCase_ == 3) && (sensorBuilder_ != null)) {
          return sensorBuilder_.getMessageOrBuilder();
        } else {
          if (messageCase_ == 3) {
            return (proto.ProtoMessageOuterClass.Sensor) message_;
          }
          return proto.ProtoMessageOuterClass.Sensor.getDefaultInstance();
        }
      }
      /**
       * <code>.proto.Sensor sensor = 3;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          proto.ProtoMessageOuterClass.Sensor, proto.ProtoMessageOuterClass.Sensor.Builder, proto.ProtoMessageOuterClass.SensorOrBuilder> 
          getSensorFieldBuilder() {
        if (sensorBuilder_ == null) {
          if (!(messageCase_ == 3)) {
            message_ = proto.ProtoMessageOuterClass.Sensor.getDefaultInstance();
          }
          sensorBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              proto.ProtoMessageOuterClass.Sensor, proto.ProtoMessageOuterClass.Sensor.Builder, proto.ProtoMessageOuterClass.SensorOrBuilder>(
                  (proto.ProtoMessageOuterClass.Sensor) message_,
                  getParentForChildren(),
                  isClean());
          message_ = null;
        }
        messageCase_ = 3;
        onChanged();;
        return sensorBuilder_;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:proto.ProtoMessage)
    }

    // @@protoc_insertion_point(class_scope:proto.ProtoMessage)
    private static final proto.ProtoMessageOuterClass.ProtoMessage DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new proto.ProtoMessageOuterClass.ProtoMessage();
    }

    public static proto.ProtoMessageOuterClass.ProtoMessage getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<ProtoMessage>
        PARSER = new com.google.protobuf.AbstractParser<ProtoMessage>() {
      public ProtoMessage parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new ProtoMessage(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<ProtoMessage> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<ProtoMessage> getParserForType() {
      return PARSER;
    }

    public proto.ProtoMessageOuterClass.ProtoMessage getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface PatientRequestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:proto.PatientRequest)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>uint32 patientNumber = 1;</code>
     */
    int getPatientNumber();
  }
  /**
   * Protobuf type {@code proto.PatientRequest}
   */
  public  static final class PatientRequest extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:proto.PatientRequest)
      PatientRequestOrBuilder {
    // Use PatientRequest.newBuilder() to construct.
    private PatientRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private PatientRequest() {
      patientNumber_ = 0;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private PatientRequest(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 8: {

              patientNumber_ = input.readUInt32();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return proto.ProtoMessageOuterClass.internal_static_proto_PatientRequest_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return proto.ProtoMessageOuterClass.internal_static_proto_PatientRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              proto.ProtoMessageOuterClass.PatientRequest.class, proto.ProtoMessageOuterClass.PatientRequest.Builder.class);
    }

    public static final int PATIENTNUMBER_FIELD_NUMBER = 1;
    private int patientNumber_;
    /**
     * <code>uint32 patientNumber = 1;</code>
     */
    public int getPatientNumber() {
      return patientNumber_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (patientNumber_ != 0) {
        output.writeUInt32(1, patientNumber_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (patientNumber_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(1, patientNumber_);
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof proto.ProtoMessageOuterClass.PatientRequest)) {
        return super.equals(obj);
      }
      proto.ProtoMessageOuterClass.PatientRequest other = (proto.ProtoMessageOuterClass.PatientRequest) obj;

      boolean result = true;
      result = result && (getPatientNumber()
          == other.getPatientNumber());
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + PATIENTNUMBER_FIELD_NUMBER;
      hash = (53 * hash) + getPatientNumber();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static proto.ProtoMessageOuterClass.PatientRequest parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static proto.ProtoMessageOuterClass.PatientRequest parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static proto.ProtoMessageOuterClass.PatientRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static proto.ProtoMessageOuterClass.PatientRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static proto.ProtoMessageOuterClass.PatientRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static proto.ProtoMessageOuterClass.PatientRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static proto.ProtoMessageOuterClass.PatientRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static proto.ProtoMessageOuterClass.PatientRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static proto.ProtoMessageOuterClass.PatientRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static proto.ProtoMessageOuterClass.PatientRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static proto.ProtoMessageOuterClass.PatientRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static proto.ProtoMessageOuterClass.PatientRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(proto.ProtoMessageOuterClass.PatientRequest prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code proto.PatientRequest}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:proto.PatientRequest)
        proto.ProtoMessageOuterClass.PatientRequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return proto.ProtoMessageOuterClass.internal_static_proto_PatientRequest_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return proto.ProtoMessageOuterClass.internal_static_proto_PatientRequest_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                proto.ProtoMessageOuterClass.PatientRequest.class, proto.ProtoMessageOuterClass.PatientRequest.Builder.class);
      }

      // Construct using proto.ProtoMessageOuterClass.PatientRequest.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        patientNumber_ = 0;

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return proto.ProtoMessageOuterClass.internal_static_proto_PatientRequest_descriptor;
      }

      public proto.ProtoMessageOuterClass.PatientRequest getDefaultInstanceForType() {
        return proto.ProtoMessageOuterClass.PatientRequest.getDefaultInstance();
      }

      public proto.ProtoMessageOuterClass.PatientRequest build() {
        proto.ProtoMessageOuterClass.PatientRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public proto.ProtoMessageOuterClass.PatientRequest buildPartial() {
        proto.ProtoMessageOuterClass.PatientRequest result = new proto.ProtoMessageOuterClass.PatientRequest(this);
        result.patientNumber_ = patientNumber_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof proto.ProtoMessageOuterClass.PatientRequest) {
          return mergeFrom((proto.ProtoMessageOuterClass.PatientRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(proto.ProtoMessageOuterClass.PatientRequest other) {
        if (other == proto.ProtoMessageOuterClass.PatientRequest.getDefaultInstance()) return this;
        if (other.getPatientNumber() != 0) {
          setPatientNumber(other.getPatientNumber());
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        proto.ProtoMessageOuterClass.PatientRequest parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (proto.ProtoMessageOuterClass.PatientRequest) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int patientNumber_ ;
      /**
       * <code>uint32 patientNumber = 1;</code>
       */
      public int getPatientNumber() {
        return patientNumber_;
      }
      /**
       * <code>uint32 patientNumber = 1;</code>
       */
      public Builder setPatientNumber(int value) {
        
        patientNumber_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>uint32 patientNumber = 1;</code>
       */
      public Builder clearPatientNumber() {
        
        patientNumber_ = 0;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:proto.PatientRequest)
    }

    // @@protoc_insertion_point(class_scope:proto.PatientRequest)
    private static final proto.ProtoMessageOuterClass.PatientRequest DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new proto.ProtoMessageOuterClass.PatientRequest();
    }

    public static proto.ProtoMessageOuterClass.PatientRequest getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<PatientRequest>
        PARSER = new com.google.protobuf.AbstractParser<PatientRequest>() {
      public PatientRequest parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new PatientRequest(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<PatientRequest> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<PatientRequest> getParserForType() {
      return PARSER;
    }

    public proto.ProtoMessageOuterClass.PatientRequest getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface PatientResponseOrBuilder extends
      // @@protoc_insertion_point(interface_extends:proto.PatientResponse)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>.proto.ProtoPatient patient = 1;</code>
     */
    boolean hasPatient();
    /**
     * <code>.proto.ProtoPatient patient = 1;</code>
     */
    proto.ProtoPatientOuterClass.ProtoPatient getPatient();
    /**
     * <code>.proto.ProtoPatient patient = 1;</code>
     */
    proto.ProtoPatientOuterClass.ProtoPatientOrBuilder getPatientOrBuilder();
  }
  /**
   * Protobuf type {@code proto.PatientResponse}
   */
  public  static final class PatientResponse extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:proto.PatientResponse)
      PatientResponseOrBuilder {
    // Use PatientResponse.newBuilder() to construct.
    private PatientResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private PatientResponse() {
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private PatientResponse(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              proto.ProtoPatientOuterClass.ProtoPatient.Builder subBuilder = null;
              if (patient_ != null) {
                subBuilder = patient_.toBuilder();
              }
              patient_ = input.readMessage(proto.ProtoPatientOuterClass.ProtoPatient.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(patient_);
                patient_ = subBuilder.buildPartial();
              }

              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return proto.ProtoMessageOuterClass.internal_static_proto_PatientResponse_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return proto.ProtoMessageOuterClass.internal_static_proto_PatientResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              proto.ProtoMessageOuterClass.PatientResponse.class, proto.ProtoMessageOuterClass.PatientResponse.Builder.class);
    }

    public static final int PATIENT_FIELD_NUMBER = 1;
    private proto.ProtoPatientOuterClass.ProtoPatient patient_;
    /**
     * <code>.proto.ProtoPatient patient = 1;</code>
     */
    public boolean hasPatient() {
      return patient_ != null;
    }
    /**
     * <code>.proto.ProtoPatient patient = 1;</code>
     */
    public proto.ProtoPatientOuterClass.ProtoPatient getPatient() {
      return patient_ == null ? proto.ProtoPatientOuterClass.ProtoPatient.getDefaultInstance() : patient_;
    }
    /**
     * <code>.proto.ProtoPatient patient = 1;</code>
     */
    public proto.ProtoPatientOuterClass.ProtoPatientOrBuilder getPatientOrBuilder() {
      return getPatient();
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (patient_ != null) {
        output.writeMessage(1, getPatient());
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (patient_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, getPatient());
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof proto.ProtoMessageOuterClass.PatientResponse)) {
        return super.equals(obj);
      }
      proto.ProtoMessageOuterClass.PatientResponse other = (proto.ProtoMessageOuterClass.PatientResponse) obj;

      boolean result = true;
      result = result && (hasPatient() == other.hasPatient());
      if (hasPatient()) {
        result = result && getPatient()
            .equals(other.getPatient());
      }
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasPatient()) {
        hash = (37 * hash) + PATIENT_FIELD_NUMBER;
        hash = (53 * hash) + getPatient().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static proto.ProtoMessageOuterClass.PatientResponse parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static proto.ProtoMessageOuterClass.PatientResponse parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static proto.ProtoMessageOuterClass.PatientResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static proto.ProtoMessageOuterClass.PatientResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static proto.ProtoMessageOuterClass.PatientResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static proto.ProtoMessageOuterClass.PatientResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static proto.ProtoMessageOuterClass.PatientResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static proto.ProtoMessageOuterClass.PatientResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static proto.ProtoMessageOuterClass.PatientResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static proto.ProtoMessageOuterClass.PatientResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static proto.ProtoMessageOuterClass.PatientResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static proto.ProtoMessageOuterClass.PatientResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(proto.ProtoMessageOuterClass.PatientResponse prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code proto.PatientResponse}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:proto.PatientResponse)
        proto.ProtoMessageOuterClass.PatientResponseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return proto.ProtoMessageOuterClass.internal_static_proto_PatientResponse_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return proto.ProtoMessageOuterClass.internal_static_proto_PatientResponse_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                proto.ProtoMessageOuterClass.PatientResponse.class, proto.ProtoMessageOuterClass.PatientResponse.Builder.class);
      }

      // Construct using proto.ProtoMessageOuterClass.PatientResponse.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        if (patientBuilder_ == null) {
          patient_ = null;
        } else {
          patient_ = null;
          patientBuilder_ = null;
        }
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return proto.ProtoMessageOuterClass.internal_static_proto_PatientResponse_descriptor;
      }

      public proto.ProtoMessageOuterClass.PatientResponse getDefaultInstanceForType() {
        return proto.ProtoMessageOuterClass.PatientResponse.getDefaultInstance();
      }

      public proto.ProtoMessageOuterClass.PatientResponse build() {
        proto.ProtoMessageOuterClass.PatientResponse result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public proto.ProtoMessageOuterClass.PatientResponse buildPartial() {
        proto.ProtoMessageOuterClass.PatientResponse result = new proto.ProtoMessageOuterClass.PatientResponse(this);
        if (patientBuilder_ == null) {
          result.patient_ = patient_;
        } else {
          result.patient_ = patientBuilder_.build();
        }
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof proto.ProtoMessageOuterClass.PatientResponse) {
          return mergeFrom((proto.ProtoMessageOuterClass.PatientResponse)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(proto.ProtoMessageOuterClass.PatientResponse other) {
        if (other == proto.ProtoMessageOuterClass.PatientResponse.getDefaultInstance()) return this;
        if (other.hasPatient()) {
          mergePatient(other.getPatient());
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        proto.ProtoMessageOuterClass.PatientResponse parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (proto.ProtoMessageOuterClass.PatientResponse) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private proto.ProtoPatientOuterClass.ProtoPatient patient_ = null;
      private com.google.protobuf.SingleFieldBuilderV3<
          proto.ProtoPatientOuterClass.ProtoPatient, proto.ProtoPatientOuterClass.ProtoPatient.Builder, proto.ProtoPatientOuterClass.ProtoPatientOrBuilder> patientBuilder_;
      /**
       * <code>.proto.ProtoPatient patient = 1;</code>
       */
      public boolean hasPatient() {
        return patientBuilder_ != null || patient_ != null;
      }
      /**
       * <code>.proto.ProtoPatient patient = 1;</code>
       */
      public proto.ProtoPatientOuterClass.ProtoPatient getPatient() {
        if (patientBuilder_ == null) {
          return patient_ == null ? proto.ProtoPatientOuterClass.ProtoPatient.getDefaultInstance() : patient_;
        } else {
          return patientBuilder_.getMessage();
        }
      }
      /**
       * <code>.proto.ProtoPatient patient = 1;</code>
       */
      public Builder setPatient(proto.ProtoPatientOuterClass.ProtoPatient value) {
        if (patientBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          patient_ = value;
          onChanged();
        } else {
          patientBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>.proto.ProtoPatient patient = 1;</code>
       */
      public Builder setPatient(
          proto.ProtoPatientOuterClass.ProtoPatient.Builder builderForValue) {
        if (patientBuilder_ == null) {
          patient_ = builderForValue.build();
          onChanged();
        } else {
          patientBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>.proto.ProtoPatient patient = 1;</code>
       */
      public Builder mergePatient(proto.ProtoPatientOuterClass.ProtoPatient value) {
        if (patientBuilder_ == null) {
          if (patient_ != null) {
            patient_ =
              proto.ProtoPatientOuterClass.ProtoPatient.newBuilder(patient_).mergeFrom(value).buildPartial();
          } else {
            patient_ = value;
          }
          onChanged();
        } else {
          patientBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>.proto.ProtoPatient patient = 1;</code>
       */
      public Builder clearPatient() {
        if (patientBuilder_ == null) {
          patient_ = null;
          onChanged();
        } else {
          patient_ = null;
          patientBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>.proto.ProtoPatient patient = 1;</code>
       */
      public proto.ProtoPatientOuterClass.ProtoPatient.Builder getPatientBuilder() {
        
        onChanged();
        return getPatientFieldBuilder().getBuilder();
      }
      /**
       * <code>.proto.ProtoPatient patient = 1;</code>
       */
      public proto.ProtoPatientOuterClass.ProtoPatientOrBuilder getPatientOrBuilder() {
        if (patientBuilder_ != null) {
          return patientBuilder_.getMessageOrBuilder();
        } else {
          return patient_ == null ?
              proto.ProtoPatientOuterClass.ProtoPatient.getDefaultInstance() : patient_;
        }
      }
      /**
       * <code>.proto.ProtoPatient patient = 1;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          proto.ProtoPatientOuterClass.ProtoPatient, proto.ProtoPatientOuterClass.ProtoPatient.Builder, proto.ProtoPatientOuterClass.ProtoPatientOrBuilder> 
          getPatientFieldBuilder() {
        if (patientBuilder_ == null) {
          patientBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              proto.ProtoPatientOuterClass.ProtoPatient, proto.ProtoPatientOuterClass.ProtoPatient.Builder, proto.ProtoPatientOuterClass.ProtoPatientOrBuilder>(
                  getPatient(),
                  getParentForChildren(),
                  isClean());
          patient_ = null;
        }
        return patientBuilder_;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:proto.PatientResponse)
    }

    // @@protoc_insertion_point(class_scope:proto.PatientResponse)
    private static final proto.ProtoMessageOuterClass.PatientResponse DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new proto.ProtoMessageOuterClass.PatientResponse();
    }

    public static proto.ProtoMessageOuterClass.PatientResponse getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<PatientResponse>
        PARSER = new com.google.protobuf.AbstractParser<PatientResponse>() {
      public PatientResponse parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new PatientResponse(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<PatientResponse> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<PatientResponse> getParserForType() {
      return PARSER;
    }

    public proto.ProtoMessageOuterClass.PatientResponse getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface SensorOrBuilder extends
      // @@protoc_insertion_point(interface_extends:proto.Sensor)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>uint32 value = 1;</code>
     */
    int getValue();
  }
  /**
   * Protobuf type {@code proto.Sensor}
   */
  public  static final class Sensor extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:proto.Sensor)
      SensorOrBuilder {
    // Use Sensor.newBuilder() to construct.
    private Sensor(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Sensor() {
      value_ = 0;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private Sensor(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 8: {

              value_ = input.readUInt32();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return proto.ProtoMessageOuterClass.internal_static_proto_Sensor_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return proto.ProtoMessageOuterClass.internal_static_proto_Sensor_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              proto.ProtoMessageOuterClass.Sensor.class, proto.ProtoMessageOuterClass.Sensor.Builder.class);
    }

    public static final int VALUE_FIELD_NUMBER = 1;
    private int value_;
    /**
     * <code>uint32 value = 1;</code>
     */
    public int getValue() {
      return value_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (value_ != 0) {
        output.writeUInt32(1, value_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (value_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(1, value_);
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof proto.ProtoMessageOuterClass.Sensor)) {
        return super.equals(obj);
      }
      proto.ProtoMessageOuterClass.Sensor other = (proto.ProtoMessageOuterClass.Sensor) obj;

      boolean result = true;
      result = result && (getValue()
          == other.getValue());
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + VALUE_FIELD_NUMBER;
      hash = (53 * hash) + getValue();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static proto.ProtoMessageOuterClass.Sensor parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static proto.ProtoMessageOuterClass.Sensor parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static proto.ProtoMessageOuterClass.Sensor parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static proto.ProtoMessageOuterClass.Sensor parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static proto.ProtoMessageOuterClass.Sensor parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static proto.ProtoMessageOuterClass.Sensor parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static proto.ProtoMessageOuterClass.Sensor parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static proto.ProtoMessageOuterClass.Sensor parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static proto.ProtoMessageOuterClass.Sensor parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static proto.ProtoMessageOuterClass.Sensor parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static proto.ProtoMessageOuterClass.Sensor parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static proto.ProtoMessageOuterClass.Sensor parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(proto.ProtoMessageOuterClass.Sensor prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code proto.Sensor}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:proto.Sensor)
        proto.ProtoMessageOuterClass.SensorOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return proto.ProtoMessageOuterClass.internal_static_proto_Sensor_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return proto.ProtoMessageOuterClass.internal_static_proto_Sensor_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                proto.ProtoMessageOuterClass.Sensor.class, proto.ProtoMessageOuterClass.Sensor.Builder.class);
      }

      // Construct using proto.ProtoMessageOuterClass.Sensor.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        value_ = 0;

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return proto.ProtoMessageOuterClass.internal_static_proto_Sensor_descriptor;
      }

      public proto.ProtoMessageOuterClass.Sensor getDefaultInstanceForType() {
        return proto.ProtoMessageOuterClass.Sensor.getDefaultInstance();
      }

      public proto.ProtoMessageOuterClass.Sensor build() {
        proto.ProtoMessageOuterClass.Sensor result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public proto.ProtoMessageOuterClass.Sensor buildPartial() {
        proto.ProtoMessageOuterClass.Sensor result = new proto.ProtoMessageOuterClass.Sensor(this);
        result.value_ = value_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof proto.ProtoMessageOuterClass.Sensor) {
          return mergeFrom((proto.ProtoMessageOuterClass.Sensor)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(proto.ProtoMessageOuterClass.Sensor other) {
        if (other == proto.ProtoMessageOuterClass.Sensor.getDefaultInstance()) return this;
        if (other.getValue() != 0) {
          setValue(other.getValue());
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        proto.ProtoMessageOuterClass.Sensor parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (proto.ProtoMessageOuterClass.Sensor) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int value_ ;
      /**
       * <code>uint32 value = 1;</code>
       */
      public int getValue() {
        return value_;
      }
      /**
       * <code>uint32 value = 1;</code>
       */
      public Builder setValue(int value) {
        
        value_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>uint32 value = 1;</code>
       */
      public Builder clearValue() {
        
        value_ = 0;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:proto.Sensor)
    }

    // @@protoc_insertion_point(class_scope:proto.Sensor)
    private static final proto.ProtoMessageOuterClass.Sensor DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new proto.ProtoMessageOuterClass.Sensor();
    }

    public static proto.ProtoMessageOuterClass.Sensor getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Sensor>
        PARSER = new com.google.protobuf.AbstractParser<Sensor>() {
      public Sensor parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new Sensor(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Sensor> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Sensor> getParserForType() {
      return PARSER;
    }

    public proto.ProtoMessageOuterClass.Sensor getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_proto_ProtoMessage_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_proto_ProtoMessage_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_proto_PatientRequest_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_proto_PatientRequest_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_proto_PatientResponse_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_proto_PatientResponse_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_proto_Sensor_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_proto_Sensor_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\022ProtoMessage.proto\022\005proto\032\022ProtoPatien" +
      "t.proto\"\236\001\n\014ProtoMessage\022/\n\016patientReque" +
      "st\030\001 \001(\0132\025.proto.PatientRequestH\000\0221\n\017pat" +
      "ientResponse\030\002 \001(\0132\026.proto.PatientRespon" +
      "seH\000\022\037\n\006sensor\030\003 \001(\0132\r.proto.SensorH\000B\t\n" +
      "\007message\"\'\n\016PatientRequest\022\025\n\rpatientNum" +
      "ber\030\001 \001(\r\"7\n\017PatientResponse\022$\n\007patient\030" +
      "\001 \001(\0132\023.proto.ProtoPatient\"\027\n\006Sensor\022\r\n\005" +
      "value\030\001 \001(\rb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          proto.ProtoPatientOuterClass.getDescriptor(),
        }, assigner);
    internal_static_proto_ProtoMessage_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_proto_ProtoMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_proto_ProtoMessage_descriptor,
        new java.lang.String[] { "PatientRequest", "PatientResponse", "Sensor", "Message", });
    internal_static_proto_PatientRequest_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_proto_PatientRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_proto_PatientRequest_descriptor,
        new java.lang.String[] { "PatientNumber", });
    internal_static_proto_PatientResponse_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_proto_PatientResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_proto_PatientResponse_descriptor,
        new java.lang.String[] { "Patient", });
    internal_static_proto_Sensor_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_proto_Sensor_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_proto_Sensor_descriptor,
        new java.lang.String[] { "Value", });
    proto.ProtoPatientOuterClass.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
